
import React from 'react';
import { TradingPair, NoTradeRule, Impact } from './types';

export const TRADING_PAIRS: TradingPair[] = [
  { id: 'EURUSD', name: 'EURUSD', category: 'Forex', currencies: ['EUR', 'USD'] },
  { id: 'GBPUSD', name: 'GBPUSD', category: 'Forex', currencies: ['GBP', 'USD'] },
  { id: 'USDJPY', name: 'USDJPY', category: 'Forex', currencies: ['USD', 'JPY'] },
  { id: 'USDCHF', name: 'USDCHF', category: 'Forex', currencies: ['USD', 'CHF'] },
  { id: 'AUDUSD', name: 'AUDUSD', category: 'Forex', currencies: ['AUD', 'USD'] },
  { id: 'NZDUSD', name: 'NZDUSD', category: 'Forex', currencies: ['NZD', 'USD'] },
  { id: 'USDCAD', name: 'USDCAD', category: 'Forex', currencies: ['USD', 'CAD'] },
  { id: 'XAUUSD', name: 'XAUUSD', category: 'Metals', currencies: ['XAU', 'USD'] },
  { id: 'XAGUSD', name: 'XAGUSD', category: 'Metals', currencies: ['XAG', 'USD'] },
  { id: 'US30', name: 'US30', category: 'Indices', currencies: ['USD'] },
  { id: 'NAS100', name: 'NAS100', category: 'Indices', currencies: ['USD'] },
  { id: 'SPX500', name: 'SPX500', category: 'Indices', currencies: ['USD'] },
  { id: 'GER40', name: 'GER40', category: 'Indices', currencies: ['EUR'] },
];

export const NO_TRADE_RULES: NoTradeRule[] = [
  { id: 'NFP', keywords: ['Non-Farm Payroll', 'NFP'], description: 'Extremely high volatility in seconds.', volatility: 3, enabled: true },
  { id: 'FOMC_RATE', keywords: ['FOMC Rate Decision', 'Interest Rate Decision'], description: 'Directs the dollar trend.', volatility: 3, enabled: true },
  { id: 'CPI', keywords: ['CPI', 'Consumer Price Index', 'Inflation'], description: 'Huge impact on central bank rates.', volatility: 3, enabled: true },
  { id: 'FOMC_CONF', keywords: ['FOMC Press Conference'], description: 'Market reactions to Q&A.', volatility: 2, enabled: true },
  { id: 'FED_POWELL', keywords: ['Powell'], description: 'Hints on monetary policy.', volatility: 2, enabled: true },
  { id: 'ECB_RATE', keywords: ['ECB Interest Rate Decision'], description: 'Major EUR movement.', volatility: 3, enabled: true },
];

export const CURRENCY_FLAGS: Record<string, string> = {
  USD: '🇺🇸',
  EUR: '🇪🇺',
  GBP: '🇬🇧',
  JPY: '🇯🇵',
  AUD: '🇦🇺',
  CAD: '🇨🇦',
  CHF: '🇨🇭',
  NZD: '🇳🇿',
  XAU: '🪙',
  XAG: '🥈',
};

export const SUPPORTED_LANGUAGES = [
  { id: 'en', name: 'English', flag: '🇺🇸' },
  { id: 'fr', name: 'Français', flag: '🇫🇷' },
  { id: 'es', name: 'Español', flag: '🇪🇸' },
  { id: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { id: 'jp', name: '日本語', flag: '🇯🇵' },
];

export const TRANSLATIONS = {
  en: {
    timeline: "Timeline",
    rules: "Rules",
    config: "Config",
    risk_restricted: "Risk Restricted",
    optimal_liquidity: "Optimal Liquidity",
    market_bias: "Market Bias",
    sentiment: "Sentiment",
    institutional_strategy: "Institutional Strategy",
    synthesize: "Synthesize Strategy",
    volatility_risk_map: "Volatility Risk Map",
    desk_ai: "Desk AI",
    brief: "Brief",
    intelligence_stream: "Intelligence Stream",
    institutional_sources: "Institutional Sources",
    verified: "Verified",
    settings: "Settings",
    language_region: "Language & Region",
    timezone: "Timezone",
    ai_profile: "AI Analyst Profile",
    risk_tolerance: "Risk Tolerance",
    alerts: "Alerts",
    push_notifications: "Push Notifications",
    alert_timing: "Alert Timing",
    trading_instruments: "Trading Instruments",
    appearance: "Appearance",
    reset_app: "Reset Application",
    secure_private: "Secure & Private · No Data Stored Online",
    what_is_notrade: "What is No-Trade?",
    notrade_desc: "Major news like NFP or FOMC create extreme volatility. 'No-Trade' alerts remind you to stay flat during these times to protect your capital.",
    active_rules: "Active Rules",
    get_started: "Get Started",
    welcome_title: "News Guard",
    welcome_desc: "The ultimate shield for your trading capital. Never miss a critical economic event again.",
    select_pairs: "Trading Pairs",
    select_pairs_desc: "Which instruments do you trade?",
    back: "Back",
    continue: "Continue",
    stay_alerted: "Stay Alerted",
    stay_alerted_desc: "Get notified 15 minutes before high-impact events.",
    enable_finish: "Enable & Finish",
    premium_neural_setup: "Premium Neural Setup",
    entry: "Entry",
    take_profit: "Take Profit",
    stop_loss: "Stop Loss",
    acknowledge: "Acknowledge Directive",
    running_models: "Running Institutional Models...",
    fcst: "FCST",
    prev: "PREV"
  },
  fr: {
    timeline: "Actualités",
    rules: "Règles",
    config: "Réglages",
    risk_restricted: "Risque Élevé",
    optimal_liquidity: "Liquidité Optimale",
    market_bias: "Biais Marché",
    sentiment: "Sentiment",
    institutional_strategy: "Stratégie Instit.",
    synthesize: "Synthétiser",
    volatility_risk_map: "Carte de Volatilité",
    desk_ai: "Analyste IA",
    brief: "Audio",
    intelligence_stream: "Flux d'Intelligence",
    institutional_sources: "Sources Institutionnelles",
    verified: "Vérifié",
    settings: "Paramètres",
    language_region: "Langue & Région",
    timezone: "Fuseau Horaire",
    ai_profile: "Profil Analyste IA",
    risk_tolerance: "Tolérance au Risque",
    alerts: "Alertes",
    push_notifications: "Notifications Push",
    alert_timing: "Délai d'Alerte",
    trading_instruments: "Instruments de Trading",
    appearance: "Apparence",
    reset_app: "Réinitialiser l'App",
    secure_private: "Sécurisé & Privé · Aucune donnée en ligne",
    what_is_notrade: "C'est quoi le No-Trade ?",
    notrade_desc: "Les annonces majeures comme le NFP créent une volatilité extrême. Ces alertes vous rappellent de rester à l'écart pour protéger votre capital.",
    active_rules: "Règles Actives",
    get_started: "Commencer",
    welcome_title: "News Guard",
    welcome_desc: "Le bouclier ultime pour votre capital. Ne manquez plus jamais un événement économique critique.",
    select_pairs: "Paires de Trading",
    select_pairs_desc: "Quels instruments tradez-vous ?",
    back: "Retour",
    continue: "Continuer",
    stay_alerted: "Restez Alerté",
    stay_alerted_desc: "Soyez notifié 15 minutes avant les événements majeurs.",
    enable_finish: "Activer & Terminer",
    premium_neural_setup: "Configuration Neurale Premium",
    entry: "Entrée",
    take_profit: "Objectif",
    stop_loss: "Stop Loss",
    acknowledge: "Compris",
    running_models: "Exécution des Modèles...",
    fcst: "PRÉV",
    prev: "PRÉC"
  },
  es: {
    timeline: "Cronología",
    rules: "Reglas",
    config: "Ajustes",
    risk_restricted: "Riesgo Restringido",
    optimal_liquidity: "Liquidez Óptima",
    market_bias: "Sesgo de Mercado",
    sentiment: "Sentimiento",
    institutional_strategy: "Estrategia Instit.",
    synthesize: "Sintetizar",
    volatility_risk_map: "Mapa de Volatilidad",
    desk_ai: "Analista IA",
    brief: "Resumen",
    intelligence_stream: "Flujo de Inteligencia",
    institutional_sources: "Fuentes Instit.",
    verified: "Verificado",
    settings: "Configuración",
    language_region: "Idioma y Región",
    timezone: "Zona Horaria",
    ai_profile: "Perfil IA",
    risk_tolerance: "Tolerancia al Riesgo",
    alerts: "Alertas",
    push_notifications: "Notificaciones Push",
    alert_timing: "Tiempo de Alerta",
    trading_instruments: "Instrumentos",
    appearance: "Apariencia",
    reset_app: "Reiniciar App",
    secure_private: "Seguro y Privado",
    what_is_notrade: "¿Qué es No-Trade?",
    notrade_desc: "Noticias como NFP crean volatilidad extrema. Estas alertas te recuerdan mantenerte fuera del mercado.",
    active_rules: "Reglas Activas",
    get_started: "Empezar",
    welcome_title: "News Guard",
    welcome_desc: "El escudo definitivo para tu capital.",
    select_pairs: "Pares de Trading",
    select_pairs_desc: "¿Qué instrumentos operas?",
    back: "Atrás",
    continue: "Continuar",
    stay_alerted: "Mantente Alerta",
    stay_alerted_desc: "Recibe notificaciones 15 min antes.",
    enable_finish: "Habilitar y Terminar",
    premium_neural_setup: "Configuración Neuronal Premium",
    entry: "Entrada",
    take_profit: "Toma de Ganancias",
    stop_loss: "Stop Loss",
    acknowledge: "Entendido",
    running_models: "Ejecutando Modelos...",
    fcst: "PREV",
    prev: "ANT"
  },
  de: {
    timeline: "Zeitlinie",
    rules: "Regeln",
    config: "Konfig",
    risk_restricted: "Risiko Eingeschränkt",
    optimal_liquidity: "Optimale Liquidität",
    market_bias: "Marktstimmung",
    sentiment: "Sentiment",
    institutional_strategy: "Instit. Strategie",
    synthesize: "Synthetisieren",
    volatility_risk_map: "Volatilitätskarte",
    desk_ai: "KI Analyst",
    brief: "Briefing",
    intelligence_stream: "Intelligenz-Stream",
    institutional_sources: "Instit. Quellen",
    verified: "Verifiziert",
    settings: "Einstellungen",
    language_region: "Sprache & Region",
    timezone: "Zeitzone",
    ai_profile: "KI Profil",
    risk_tolerance: "Risikotoleranz",
    alerts: "Benachrichtigungen",
    push_notifications: "Push-Nachrichten",
    alert_timing: "Alarmzeit",
    trading_instruments: "Handelsinstrumente",
    appearance: "Erscheinungsbild",
    reset_app: "App Zurücksetzen",
    secure_private: "Sicher & Privat",
    what_is_notrade: "Was ist No-Trade?",
    notrade_desc: "Große Nachrichten verursachen Volatilität. Diese Warnungen schützen Ihr Kapital.",
    active_rules: "Aktive Regeln",
    get_started: "Loslegen",
    welcome_title: "News Guard",
    welcome_desc: "Der ultimative Schutz für Ihr Handelskapital.",
    select_pairs: "Handelspaare",
    select_pairs_desc: "Welche Instrumente handeln Sie?",
    back: "Zurück",
    continue: "Weiter",
    stay_alerted: "Bleiben Sie alarmiert",
    stay_alerted_desc: "Werden Sie 15 Minuten vorher benachrichtigt.",
    enable_finish: "Aktivieren & Beenden",
    premium_neural_setup: "Premium Neuronales Setup",
    entry: "Einstieg",
    take_profit: "Gewinnmitnahme",
    stop_loss: "Stop Loss",
    acknowledge: "Verstanden",
    running_models: "Führe Modelle aus...",
    fcst: "PROG",
    prev: "VORH"
  },
  jp: {
    timeline: "タイムライン",
    rules: "ルール",
    config: "設定",
    risk_restricted: "リスク制限",
    optimal_liquidity: "最適流動性",
    market_bias: "市場バイアス",
    sentiment: "センチメント",
    institutional_strategy: "機関戦略",
    synthesize: "戦略合成",
    volatility_risk_map: "ボラティリティマップ",
    desk_ai: "AIアナリスト",
    brief: "ブリーフィング",
    intelligence_stream: "インテリジェンス",
    institutional_sources: "情報源",
    verified: "確認済み",
    settings: "設定",
    language_region: "言語と地域",
    timezone: "タイムゾーン",
    ai_profile: "AIプロファイル",
    risk_tolerance: "リスク許容度",
    alerts: "アラート",
    push_notifications: "プッシュ通知",
    alert_timing: "アラート時間",
    trading_instruments: "取引商品",
    appearance: "外観",
    reset_app: "アプリをリセット",
    secure_private: "安全でプライベート",
    what_is_notrade: "ノートレードとは？",
    notrade_desc: "NFPのようなニュースは極端な変動を引き起こします。これらのアラートは資金を守るために待機を促します。",
    active_rules: "アクティブルール",
    get_started: "始める",
    welcome_title: "News Guard",
    welcome_desc: "取引資金のための究極の盾。",
    select_pairs: "取引ペア",
    select_pairs_desc: "どの商品を取引しますか？",
    back: "戻る",
    continue: "次へ",
    stay_alerted: "アラート維持",
    stay_alerted_desc: "重要なイベントの15分前に通知を受け取ります。",
    enable_finish: "有効化して終了",
    premium_neural_setup: "プレミアムニューラルセットアップ",
    entry: "エントリー",
    take_profit: "利益確定",
    stop_loss: "損切り",
    acknowledge: "了解",
    running_models: "モデル実行中...",
    fcst: "予想",
    prev: "前回"
  }
};
